#!/bin/bash

sighandl() {
	trap "echo Received $1. Exiting...; vncserver -kill :0; exit;" $1
}

for sig in SIGINT SIGTERM; do sighandl $sig; done

vncserver :0
/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 80 &

while :; do :; done
